### ISSUE TITLE
add Laravel Collective dependency

### ISSUE THREAD

**Issue by bhirons** [coopers98/genericcrud#1]
The views require "laravelcollective/html": "~5.0" for helper and Form macros.  

Please consider adding this dependency to your composer.json file since these things are no longer included by default in vanilla Laravel 5.1

**Comment by coopers98** [comment]
Good call, thanks!  My first time putting a package together so will definitely be a learning experience

**Comment by coopers98** [comment]
Added as a dependancy

**Comment by coopers98** [comment]
I could rewrite the views to not use the Forms helpers to help cull a dependency.  I'm curious of your thoughts on the matter?

**Comment by bhirons** [comment]
I think it is OK to have this dependency.  It is widely accepted and I use it myself for one-off forms.  I think the only reason you didn't add it originally is because almost everyone adds it already anyway :)
